# Generated by Django 3.2 on 2021-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_path', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=255)),
                ('request_execution_time', models.FloatField()),
            ],
        ),
    ]
