# Generated by Django 3.2 on 2021-05-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_logger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
